version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001
  backend:
    build: ./flask-server
    ports:
      - "5001:5001"
